import '../styles/index.scss'
// import './01.templateString.js'
// import './02.letConstVar'
// import './03.arrowFunction'
// import './04.arrowFunctionThis'
// import './05.defaultParameters'
// import './06.iterableObject'
// import './07.restSpread'
// import './08.enhanceObject'
// import './09.destructuring'
// import './10.objectEntries'
// import './11.symbols'
// import './12.iteratorBasics'
// import './13.iteratorSymbol'
// import './14.forOfLoop'
// import './15.generators'
// import './16.set'
// import './17.map'
// import './18.weakSet'
// import './19.weakMap'
// import './20.class'
import './21.classProperties'